# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  tags:
    include: ["*"] #S35

pool:
  vmImage: ubuntu-latest

steps:
- task: UniversalPackages@0
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.SourcesDirectory)'
    feedsToUsePublish: 'internal'
    vstsFeedPublish: '736b4ce8-9eaf-495c-9983-ed63d9930834'
    vstsFeedPackagePublish: 'frontend'
    versionOption: 'patch'
