# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
 tags:
   include: ["*"] # triggers with all tags

pool: Default  #self hosted pool

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |        #selected components or files will copy to publish dir..
      mkdir publish
      cp -r components launch-instances.sh publish
- task: UniversalPackages@0  #publish frontend artifactory
  inputs:
    command: 'publish'
    publishDirectory: '$(Build.SourcesDirectory)/publish'  # here download only publish directory
    feedsToUsePublish: 'internal'
    vstsFeedPublish: '736b4ce8-9eaf-495c-9983-ed63d9930834'
    vstsFeedPackagePublish: 'frontend'
    versionOption: 'patch'
